development:
  adapter: postgresql
  encoding: unicode
  database: twizzler
  pool: 5
  username: root
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1